name: CI

on:
  push:
    paths:
      - '**.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run a one-line script
      run: echo Workflow starting...

    ## Setting an output parameter
    - name: Set color
      id: color-selector
      run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
    
    - name: Get color 1
      run: echo "The selected color is ${{ steps.color-selector.outputs.SELECTED_COLOR }}"

    - name: Get color 2
      run: |
          SELECTED_COLOR=${{ steps.color-selector.outputs.SELECTED_COLOR }}
          echo "The selected color is $SELECTED_COLOR"

    - name: Get color 3
      run: echo "MY_ENV_VAR=${{ steps.color-selector.outputs.SELECTED_COLOR }}" >> $GITHUB_ENV

    - name: Use environment variable 4
      run: echo $MY_ENV_VAR

    - name: Use environment variable 5
      run: echo "The selected color is " $MY_ENV_VAR
      
