name: CI

on:
  push:
    paths:
      - '3-**.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Let's Go!

    ## Adding a job summary
    - name: Add job summary
      run: |
        echo "{markdown content}" >> $GITHUB_STEP_SUMMARY
        echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY

    - name: Generate list using Markdown
      run: |
        echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
        
